version: "3.3"
   
services:
    task:
        build: .
        container_name: task
        command: python3 code/main.py
        volumes:
            - logs:/app/logs
        environment:
            - LOG_FILE=logs/logs.log
            - POSTGRES_DB=coinDB
            - POSTGRES_USER=coinTask
            - POSTGRES_PASSWORD=coin123
            - POSTGRES_HOST=pgdb
            - POSTGRES_PORT=5432
        env_file:
            - env/task.env
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=coinDB
            - POSTGRES_USER=coinTask
            - POSTGRES_PASSWORD=coin123
        volumes:
            - pgdata:/var/lib/postgresql/data/
        ports: 
            - '5432:5432'
volumes:
    logs:
    pgdata: