version: "3.3"
   
services:
    task:
        build: .
        container_name: task
        command: python3 code/main.py
        volumes:
            - .:/usr/src/app/
            - .:/usr/src/logs/
        environment:
            - LOG_FILE=logs/logs.log
            - POSTGRES_DB=coinDB
            - POSTGRES_USER=coinTask
            - POSTGRES_PASSWORD=coin123
            - POSTGRES_HOST=127.0.0.1
            - POSTGRES_PORT=5432
            - API_KEY=9f4f9d88-3032-4457-9f7d-d4e597df7819
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=coinDB
            - POSTGRES_USER=coinTask
            - POSTGRES_PASSWORD=coin123
        volumes:
            - pgdata:/var/lib/postgresql/data/
volumes:
    pgdata: